import { Conversation } from './types';

export const CURRENT_USER_ID = 'me';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    person: {
      id: 'p1',
      name: 'Priya Sharma',
      subtitle: 'Fashion & Lifestyle Creator',
      avatar: '',
      location: 'Mumbai, India',
      company: 'StyleWithPriya',
      role: 'Content Creator',
      email: 'priya@stylewithpriya.in',
      niche: 'Fashion & Lifestyle',
      followers: '245K',
      joined: 'Jan 2024',
      bio: 'Fashion enthusiast sharing everyday style tips and sustainable fashion finds. Collaborated with 30+ brands across India.',
    },
    messages: [
      { id: 'm1', senderId: 'p1', text: 'Hi! I saw your brand profile on ReachEzy. Love your products!', timestamp: '10:00 AM' },
      { id: 'm2', senderId: CURRENT_USER_ID, text: 'Thanks Priya! We\'d love to explore a collaboration with you.', timestamp: '10:05 AM' },
      { id: 'm3', senderId: 'p1', text: 'That sounds great! What kind of campaign are you thinking about?', timestamp: '10:08 AM' },
      { id: 'm4', senderId: CURRENT_USER_ID, text: 'We\'re launching a new summer collection and need Instagram Reels + Stories. Would that work for you?', timestamp: '10:12 AM' },
      { id: 'm5', senderId: 'p1', text: 'Absolutely! I love doing Reels. Could you share the product details and timeline?', timestamp: '10:15 AM' },
      { id: 'm6', senderId: CURRENT_USER_ID, text: 'Sure! I\'ll send over the brief by tomorrow. The campaign runs from March 15 to April 15.', timestamp: '10:18 AM' },
      { id: 'm7', senderId: 'p1', text: 'Perfect, looking forward to it! 🙌', timestamp: '10:20 AM' },
    ],
    lastMessage: 'Perfect, looking forward to it! 🙌',
    lastMessageTime: '10:20 AM',
  },
  {
    id: '2',
    person: {
      id: 'p2',
      name: 'Arjun Mehta',
      subtitle: 'Tech & Gadget Reviewer',
      avatar: '',
      location: 'Bangalore, India',
      company: 'TechWithArjun',
      role: 'YouTuber & Reviewer',
      email: 'arjun@techwith.in',
      niche: 'Technology',
      followers: '512K',
      joined: 'Mar 2023',
      bio: 'India\'s go-to tech reviewer. Honest reviews on smartphones, laptops, and gadgets. 500+ videos on YouTube.',
    },
    messages: [
      { id: 'm8', senderId: CURRENT_USER_ID, text: 'Hey Arjun, loved your review of the new Pixel phone!', timestamp: 'Yesterday' },
      { id: 'm9', senderId: 'p2', text: 'Thanks! Are you looking for a product review collaboration?', timestamp: 'Yesterday' },
      { id: 'm10', senderId: CURRENT_USER_ID, text: 'Yes! We have a new wireless earbuds line launching next month.', timestamp: 'Yesterday' },
      { id: 'm11', senderId: 'p2', text: 'Interesting! What\'s the price range and target audience?', timestamp: 'Yesterday' },
      { id: 'm12', senderId: CURRENT_USER_ID, text: 'Rs 2,999 - Rs 4,999 range, targeting young professionals and students.', timestamp: 'Yesterday' },
      { id: 'm13', senderId: 'p2', text: 'That\'s right in my audience sweet spot. Send me a sample and I\'ll do an honest review.', timestamp: 'Yesterday' },
    ],
    lastMessage: 'That\'s right in my audience sweet spot. Send me a sample and I\'ll do an honest review.',
    lastMessageTime: 'Yesterday',
  },
  {
    id: '3',
    person: {
      id: 'p3',
      name: 'Neha Kapoor',
      subtitle: 'Food & Travel Blogger',
      avatar: '',
      location: 'Delhi, India',
      company: 'NehaExplores',
      role: 'Blogger & Influencer',
      email: 'neha@nehaexplores.com',
      niche: 'Food & Travel',
      followers: '180K',
      joined: 'Jun 2023',
      bio: 'Exploring hidden food gems and travel spots across India. Featured in Times Food and Condé Nast Traveller India.',
    },
    messages: [
      { id: 'm14', senderId: 'p3', text: 'Hi there! I\'m interested in partnering for a restaurant review series.', timestamp: 'Mar 1' },
      { id: 'm15', senderId: CURRENT_USER_ID, text: 'That sounds exciting! We have 5 new outlets opening in Delhi NCR.', timestamp: 'Mar 1' },
      { id: 'm16', senderId: 'p3', text: 'Oh wow, I\'d love to cover the launches! What cuisine?', timestamp: 'Mar 1' },
      { id: 'm17', senderId: CURRENT_USER_ID, text: 'Modern Indian fusion. Think butter chicken pizza and tandoori tacos! 😄', timestamp: 'Mar 1' },
      { id: 'm18', senderId: 'p3', text: 'Haha that sounds amazing! Count me in. Let\'s set up a call this week?', timestamp: 'Mar 1' },
    ],
    lastMessage: 'Haha that sounds amazing! Count me in. Let\'s set up a call this week?',
    lastMessageTime: 'Mar 1',
  },
  {
    id: '4',
    person: {
      id: 'p4',
      name: 'Rohan Desai',
      subtitle: 'Fitness & Wellness Coach',
      avatar: '',
      location: 'Pune, India',
      company: 'FitWithRohan',
      role: 'Fitness Influencer',
      email: 'rohan@fitwithrohan.in',
      niche: 'Fitness & Wellness',
      followers: '320K',
      joined: 'Sep 2023',
      bio: 'Certified fitness trainer helping people transform their lives. Specializing in home workouts and nutrition planning.',
    },
    messages: [
      { id: 'm19', senderId: 'p4', text: 'Hey! I saw you\'re looking for fitness creators for your protein brand.', timestamp: 'Feb 28' },
      { id: 'm20', senderId: CURRENT_USER_ID, text: 'Yes! Your content style is exactly what we\'re looking for.', timestamp: 'Feb 28' },
      { id: 'm21', senderId: 'p4', text: 'Great! I only promote products I personally use and believe in. Can I try the products first?', timestamp: 'Feb 28' },
      { id: 'm22', senderId: CURRENT_USER_ID, text: 'Absolutely, we\'ll send a full range of samples. We value authentic reviews.', timestamp: 'Feb 28' },
    ],
    lastMessage: 'Absolutely, we\'ll send a full range of samples. We value authentic reviews.',
    lastMessageTime: 'Feb 28',
  },
  {
    id: '5',
    person: {
      id: 'p5',
      name: 'Ananya Iyer',
      subtitle: 'Beauty & Skincare Expert',
      avatar: '',
      location: 'Chennai, India',
      company: 'GlowWithAnanya',
      role: 'Beauty Creator',
      email: 'ananya@glowwithananya.in',
      niche: 'Beauty & Skincare',
      followers: '410K',
      joined: 'Nov 2022',
      bio: 'Dermatologist-turned-creator breaking down skincare science in simple terms. Trusted by 400K+ for honest product reviews.',
    },
    messages: [
      { id: 'm23', senderId: CURRENT_USER_ID, text: 'Hi Ananya! We\'re a new clean beauty brand and would love to work with you.', timestamp: 'Feb 25' },
      { id: 'm24', senderId: 'p5', text: 'Hi! I\'d love to learn more. What are your key ingredients and certifications?', timestamp: 'Feb 25' },
      { id: 'm25', senderId: CURRENT_USER_ID, text: 'All products are dermatologically tested, vegan, and cruelty-free. Key ingredients include niacinamide, hyaluronic acid, and vitamin C.', timestamp: 'Feb 25' },
      { id: 'm26', senderId: 'p5', text: 'Those are solid ingredients! I\'d want to test them for at least 2 weeks before creating content. Is that timeline okay?', timestamp: 'Feb 25' },
      { id: 'm27', senderId: CURRENT_USER_ID, text: 'Of course! We want genuine results. Take your time.', timestamp: 'Feb 25' },
      { id: 'm28', senderId: 'p5', text: 'Love that approach. Send them over and I\'ll start my testing protocol!', timestamp: 'Feb 25' },
    ],
    lastMessage: 'Love that approach. Send them over and I\'ll start my testing protocol!',
    lastMessageTime: 'Feb 25',
  },
];
